
version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: yarn dev 
    container_name: frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/index.html:/usr/src/app/index.html
    ports:
      - "3000:3000"

