
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - .:/backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: yarn preview 
    container_name: frontend
    volumes:
      - .:/frontend
    ports:
      - "3000:3000"
